#!/bin/sh
# Cross-compile Steb for the Kindle and stage the device mirror for a USB copy.
#
#   ./build.sh
#
# Produces device/ ready to drag onto the Kindle's USB volume:
#
#   device/extensions/steb/   -> /mnt/us/extensions/steb/
#   device/documents/Steb.sh  -> /mnt/us/documents/Steb.sh
#
# One armv7 musl binary covers the whole fleet — KOA2, Colorsoft and Scribe all
# run a 32-bit armv7 userspace, and static linking makes it firmware-agnostic.
#
# No C toolchain is needed. That is not automatic: TLS normally drags in `ring`,
# whose C build script would break rust-lld and force the whole build through
# zig. It is avoided by taking ureq's `rustls-no-provider` feature and supplying
# the pure-Rust RustCrypto provider instead — see native/Cargo.toml.
set -eu

TARGET="armv7-unknown-linux-musleabihf"
ROOT="$(cd "$(dirname "$0")" && pwd)"
OUT="$ROOT/device/extensions/steb/bin/steb"

# Surface a missing cross target as one line rather than cargo's opaque
# "can't find core for armv7-…" panic.
if ! rustup target list --installed | grep -qx "$TARGET"; then
    echo "error: rustup target '$TARGET' is not installed" >&2
    echo "       fix: rustup target add $TARGET" >&2
    exit 1
fi

# rust-lld ships inside the toolchain but is not on PATH by default, and the
# host triple differs between Intel and Apple Silicon, so resolve it here rather
# than hardcoding it in .cargo/config.toml.
if ! command -v rust-lld >/dev/null 2>&1; then
    echo "error: rust-lld is not on PATH" >&2
    echo "       fix: ln -sf \"\$(rustc --print sysroot)/lib/rustlib/\$(rustc -vV | awk '/^host:/ {print \$2}')/bin/rust-lld\" ~/.cargo/bin/rust-lld" >&2
    exit 1
fi

# Single source of truth for the version: [workspace.package] in Cargo.toml.
# Everything in the binary picks it up through CARGO_PKG_VERSION — the user
# agent, the startup log line — but KUAL reads config.xml, which cargo knows
# nothing about. Stamp it here so the two cannot drift; a hand-maintained copy
# would sit at the old number for exactly as long as nobody looked.
VERSION="$(awk '/^\[workspace\.package\]/{f=1;next} /^\[/{f=0}
                f && /^version *=/{gsub(/[" ]/,""); sub(/^version=/,""); print; exit}' \
    "$ROOT/Cargo.toml")"
[ -n "$VERSION" ] || { echo "error: no version in [workspace.package]" >&2; exit 1; }

CONFIG="$ROOT/device/extensions/steb/config.xml"
if [ -f "$CONFIG" ]; then
    TMP="$(mktemp)"
    sed "s|<version>[^<]*</version>|<version>$VERSION</version>|" "$CONFIG" > "$TMP"
    cat "$TMP" > "$CONFIG"
    rm -f "$TMP"
fi

echo "==> building steb $VERSION for $TARGET"
cargo build --release --target "$TARGET" -p steb-native --bin steb-native

# Named `steb` on device, not `steb-native`: the tile's single-instance guard
# is `pidof steb`, and bin/steb.sh execs that name. The cargo target keeps the
# longer name so a host build cannot collide with it.
mkdir -p "$(dirname "$OUT")"
cp "$ROOT/target/$TARGET/release/steb-native" "$OUT"
chmod +x "$OUT" 2>/dev/null || true

echo "==> staged $(ls -lh "$OUT" | awk '{print $5}') -> device/extensions/steb/bin/steb"
file "$OUT" 2>/dev/null || true

# The scriptlet is deliberately NOT rebuilt here. Its `# Icon:` line is a ~21KB
# base64 blob regenerated by device/make-tile.sh, which needs rsvg-convert and
# pngquant — dependencies the build has no business requiring — and rewriting a
# committed file on every build would churn that line into every diff. The tile
# ships with the icon already embedded, so it is installable as it stands.
#
# What is worth catching is a *stale* one: edit the cover, forget make-tile.sh,
# and the old art ships silently. So check rather than regenerate.
TILE="$ROOT/device/documents/Steb.sh"
COVER="$ROOT/device/assets/cover.png"
if ! grep -q '^# Icon: data:image/png;base64,' "$TILE" 2>/dev/null; then
    echo "warning: $TILE has no embedded cover — run device/make-tile.sh" >&2
elif [ -f "$COVER" ] && [ "$COVER" -nt "$TILE" ]; then
    echo "warning: assets/cover.png is newer than the tile's embedded icon" >&2
    echo "         the old cover would ship — run device/make-tile.sh" >&2
fi

cat <<'EOF'

==> install — copy these two onto the device

    device/extensions/steb/    ->  /mnt/us/extensions/steb/
    device/documents/Steb.sh   ->  /mnt/us/documents/Steb.sh

Books land in /mnt/us/documents/standardebooks/.
Logs, if anything goes wrong, in /mnt/us/steb.log.
EOF
